### ISSUE TITLE
Reviews

### ISSUE THREAD

**Issue by Aaryanpal** [ArvindO07/Car-Parking-Management-System-Using-Cpp#1]
## Hi Arvind , I found your post on LeetCode , this is a small suggestion:
1. Use UML Diagram in your Readme so that Project Will Be More Informative.
2. Deploy your Project on  [Repel](https://replit.com/) and add it in Description
## Add-On

1. A Short GIF of your GUI application Working will be a Cherry on Top if you could do that.

**Comment by ArvindO07** [comment]
thank you for this information now i am starting work on it
